import = ["~/.config/alacritty/themes/rose-pine.toml"]
[env]
TERM                = "xterm-256color"

[window]
decorations         = "Buttonless" 
opacity             = 0.75 
dimensions          = { columns = 80, lines = 24 }
padding             = { x = 2, y = 2 }


# Spread additional padding evenly around the terminal content.
dynamic_padding     = true

# When true, alacritty starts maximized.
startup_mode        = "maximized"


[scrolling]
history           = 100000
multiplier        = 3

transparent_background_colors = true


[font]
normal            = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold              = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic            = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size              = 11.0
offset            = { x = 0, y = 0 }

