[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 1.0


# Spread additional padding evenly around the terminal content.
dynamic_padding = true

# When true, alacritty starts maximized.
startup_mode = "maximized"

# multiplier = 3

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[terminal]
shell = { program = "pwsh", args = ["-NoLogo"] }

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 10.0
offset = { x = 0, y = 0 }

[general]
import = ["~/.config/alacritty/themes/rose-pine.toml"]
working_directory = "C:/code"
